# Setup
title:        SilvDev
tagline:      Java developing
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Loeana
  url:        http://silvdev.pl 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
